spring:
  cloud:
    function:
      task:
        supplier: words
        function: uppercase
        consumer: print        
      compile:
        words:
          type: supplier
          lambda: ()->Flux.just("hello","world")
        uppercase:
          lambda: s->s.toUpperCase()
          inputType: String
          outputType: String
        print:
          type: consumer
          lambda: System.out::println
          inputType: String
